data: configs/data/bubble_train_dev.yaml
eval_data: yolo_dataset_grouped/bubble.yaml
project: runs/bubble
imgsz: 640
epochs: 100
batch: 16
workers: 8
device: 0,1
seed: 42
patience: 30
optimizer: SGD
lr0: 0.001
momentum: 0.937
weight_decay: 0.0005
cos_lr: true
close_mosaic: 10
save_period: 10
plots: true
amp: true
val: true
predict: true
predict_conf: 0.25
predict_iou: 0.60
freeze: 10
mosaic: 0.0
mixup: 0.0
copy_paste: 0.0
hsv_h: 0.005
hsv_s: 0.15
hsv_v: 0.15
degrees: 0.0
translate: 0.03
scale: 0.1
fliplr: 0.5
flipud: 0.0
